# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "prometheus" do |prometheus|
    prometheus.vm.hostname = "prometheus"
    prometheus.vm.box = "bento/centos-8"
    prometheus.vm.box_check_update = false

    prometheus.vm.network "private_network", ip: "192.168.56.90"
    # config.vm.synced_folder "../data", "/vagrant_data"

    prometheus.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "prometheus"
      vb.cpus = 2
      vb.memory = "2048"
    end

    prometheus.vm.provision "shell", path: "./scripts/common.sh"

    prometheus.vm.provision "shell", privileged: false, inline: <<-SHELL
      echo "prometheus server is ready!!!"
    SHELL
  end

  (1..2).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.hostname = "worker-#{i}"
      node.vm.box = "bento/centos-8"
      node.vm.box_check_update = false

      node.vm.network "private_network", ip: "192.168.56.1#{i}"

      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.name = "node-#{i}"
        vb.cpus = 2
        vb.memory = "1024"  
      end

      node.vm.provision "shell", path: "./scripts/common.sh"

      node.vm.provision "shell", privileged: false, inline: <<-SHELL        
        echo "node exporter is ready!!!"
      SHELL
    end
  end

end
