route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'send_email'

receivers:
  - name: 'send_email'
    email_configs:
      - to: prometheus_demo@corp.net
        from: sender@corp.net
        smarthost: mail.corp.net:465
        auth_username: sender@corp.net
        auth_password: P@ssword
        require_tls: false

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
