---
- hosts: labservers
  vars:
    http_service: httpd
    http_port: 80
    http_user: apache
    http_group: apache
    max_client: 200
  # remote_user: root
  become: true
  tasks:
    - name: ensure apache is at the latest version
      yum:
        name: "{{ http_service }}"
        state: latest
    - name: write welcome page
      template:
        src: ./welcome.html.j2
        dest: /var/www/html/index.html
        owner: "{{ http_user }}"
        group: "{{ http_group }}"
        mode: 0644
      notify: 
        - restart apache
    - name: ensure apache is running
      service:
        name: "{{ http_service }}"
        state: started
  handlers:
    - name: restart apache
      service:
        name: "{{ http_service }}"
        state: restarted